#!/usr/bin/env python

# Usage:
#   pyrun 'pkg.module.RunnerClass' [runner options]
#

from sys import argv

def get_class(runner_module_string):
    """
    Ganked from: http://stackoverflow.com/questions/452969/does-python-have-an-equivalent-to-java-class-forname
    """
    parts = kls.split('.')
    module = ".".join(parts[:-1])
    m = __import__( module )
    for comp in parts[1:]:
        m = getattr(m, comp)
    return m

if __name__ == '__main__':
    runner_arg = argv[1]
    del argv[1]
    runner_class = get_class(runner_arg)
    return(runner_class().run())
